### ISSUE TITLE
See signatures does not work

### ISSUE THREAD

**Issue by hoenn321** [CSE442-SPEAK/speak#70]
See signatures does not work when clicking. Has a long string [{"signature_id":3,"petition_id":1,"user_id":2},{"signature_id":7,"petition_id":1,"user_id":1},{"signature_id":8,"petition_id":1,"user_id":1},{"signature_id":9,"petition_id":1,"user_id":1},{"signature_id":10,"petition_id":1,"user_id":1},{"signature_id":17,"petition_id":1,"user_id":1}]. Probably a placeholder that shouldn't appear in the front end.

**Comment by hjkaria** [comment]
Thank you for filing an issue. We have been having issues with having the signatures display correctly, but since this has been filed we've removed the "See Signatures" button so the array of signatures no longer appears
