### ISSUE TITLE
I can't log in after registration.

### ISSUE THREAD

**Issue by QinxinTian** [CSE442-SPEAK/speak#75]
[Screen Capture 1.mov.zip](https://github.com/CSE442-SPEAK/speak/files/1443097/Screen.Capture.1.mov.zip)

**Comment by wenxuans** [comment]
Our authentication is currently not up yet, hence why log-in and sign-up don't work. We are working on that though.

**Comment by hjkaria** [comment]
Authentication and login / signup are now supported thru Auth0. #98
