### ISSUE TITLE
The login function is not working. I can't log in with very normal registration process as filling every field in a correct way.

### ISSUE THREAD

**Issue by QinxinTian** [CSE442-SPEAK/speak#76]
[Screen Capture 2.mov.zip](https://github.com/CSE442-SPEAK/speak/files/1443098/Screen.Capture.2.mov.zip)

**Comment by jf-ub** [comment]
+1

**Comment by wenxuans** [comment]
Our authentication is currently not up yet, hence why log-in and sign-up don't work. We are working on it though.

**Comment by hjkaria** [comment]
You now can login through Auth0. #98
