### ISSUE TITLE
This site is not secure

### ISSUE THREAD

**Issue by QinxinTian** [CSE442-SPEAK/speak#78]
<img width="1274" alt="2017-11-04 10 57 06" src="https://user-images.githubusercontent.com/25886116/32411547-f34b65ac-c1b3-11e7-923e-72b110e365b5.png">
Look at the left of the URL. It should be green if it is secure.

**Comment by wenxuans** [comment]
We are using HTTPS so I'm not sure why it's listed as not secure, but we will look into it. Thanks!

**Comment by hjkaria** [comment]
Site is now secure through Auth0: 
![image](https://user-images.githubusercontent.com/14285726/33287706-9176c7b4-d387-11e7-978c-aebde389cea2.png)

![image](https://user-images.githubusercontent.com/14285726/33287738-aae331a6-d387-11e7-9a89-4c56fe4437ca.png)
