### ISSUE TITLE
Bug Report: Can't Login After Registering

### ISSUE THREAD

**Issue by singularity471** [CSE442-SPEAK/speak#81]
I cannot login after making an account -- at least there is no indication that I have logged in.  

This is what I see after clicking login using an account I have registered:

![image](https://user-images.githubusercontent.com/14144563/32415788-649900bc-c20d-11e7-8e40-78e0fcd64726.png)

**Comment by wenxuans** [comment]
Our authentication is currently not up yet, hence why log-in and sign-up don't work. We are working on it though!

**Comment by hjkaria** [comment]
Authentication and login / signup are now supported thru Auth0. #98
