### ISSUE TITLE
Bug Report: Signing multiple times

### ISSUE THREAD

**Issue by nitgarg99** [CSE442-SPEAK/speak#82]
I'm pretty sure you can sign the petition multiple times. If not, the pop-up should be changed to say "you've already signed" or something along those lines. Maybe this just gets fixed by fixing the other bug about not having to sign in.

**Comment by wenxuans** [comment]
Yes, our authentication is currently not up yet, hence why log-in and sign-up don't work. Once we have it up, we can enforce petition signing as well.

**Comment by hjkaria** [comment]
Authentication and login / signup are now supported thru Auth0. #98 Next step is to enforce single signing

**Comment by hjkaria** [comment]
User can only sign petition once.
