### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by kjwong2018** [CSE442-SPEAK/speak#86]
Looking at all the issue you have for can't log in/sign up I recommend using OAuth and also no sign up implementation. 

If your platform is only for UB, use OAuth and check if email ends with buffalo.edu. No sign up is needed.

The website created by my friend for Course Radar uses this concept.
https://courseradar.firebaseapp.com/search.html

**Comment by wenxuans** [comment]
Hi Kevin, thanks for the input! We actually have been trying to implement OAuth, but are just having some issues integrating it with our app. The log-in/sign-up buttons were simply placeholders on the website until we could get OAuth up and running.

**Comment by kjwong2018** [comment]
Good luck!
